pipeline{
    agent any
    tools{
        maven 'maven'
    }
    stages{
        stage("clone")
        {
            steps{
                git 'https://github.com/vPt-King/project-vnpt.git'
            }
        }
        stage("test")
        {
            steps{
                sh "mvn -f web/pom.xml clean test"
            }
        }
        stage("build")
        {
            steps{
                sh "mvn -f web/pom.xml clean install"
            }
        }
        stage("build and push image")
        {
            steps{
                withDockerRegistry(credentialsId: '573f4d52-0eea-43a5-95bc-fa8dda139b5b', url: 'https://index.docker.io/v1/') {
                    sh "docker build -f Dockerfile -t thanhvu638/project:${BUILD_ID} ../javaweb/"
                    sh "docker push thanhvu638/project:${BUILD_ID}"
                }
            }
        }
        stage("ansible")
        {
            steps{
                sh "/usr/bin/ansible-playbook /var/lib/jenkins/workspace/project/ansible/ansible.yml -i /var/lib/jenkins/workspace/project/ansible/inventory.ini -e \"version=${BUILD_ID}\""
            }
        }
    }
}